### PR TITLE
Made necessary changes for cross platform compatibility

### PR DESCRIPTION
**Pull request by jraad**
Definition of max function was causing compiler issues. Standard max function wasn't working on linux so switch max to fmax.

### CODE REVIEW

**Comment by FilippoBovo** [comment]
Hey, @jraad. Thanks for the pull request.

Could you paste here the compiler error? Also, what compiler are you using?

**Comment by jraad** [comment]
Hey @FilippoBovo thanks for reaching out! The build was failing on Windows using version 14 of the C build tools, and it failed on Linux using GCC. I found that defining the max function in base.c was causing the Windows error, and not using the fmax function was causing the error on Linux. Compiling error on Windows is below:

`ERROR: Command errored out with exit status 1:
     command: 'c:\users\jraad\appdata\local\programs\python\python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\jraad\\AppData\\Local\\Temp\\pip-req-build-3zgly3fq\\setup.py'"'"'; __file__='"'"'C:\\Users\\jraad\\AppData\\Local\\Temp\\pip-req-build-3zgly3fq\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\jraad\AppData\Local\Temp\pip-record-uvx51511\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\jraad\appdata\local\programs\python\python37\Include\robustats'
         cwd: C:\Users\jraad\AppData\Local\Temp\pip-req-build-3zgly3fq\
    Complete output (23 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\robustats
    copying robustats\robustats.py -> build\lib.win-amd64-3.7\robustats
    copying robustats\__init__.py -> build\lib.win-amd64-3.7\robustats
    running build_ext
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    building '_robustats' extension
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    creating build\temp.win-amd64-3.7\Release\c
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\jraad\appdata\local\programs\python\python37\lib\site-packages\numpy\core\include -Ic:\users\jraad\appdata\local\programs\python\python37\include -Ic:\users\jraad\appdata\local\programs\python\python37\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /Tcc/_robustats.c /Fobuild\temp.win-amd64-3.7\Release\c/_robustats.obj -std=c99
    cl : Command line warning D9002 : ignoring unknown option '-std=c99'
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\jraad\appdata\local\programs\python\python37\lib\site-packages\numpy\core\include -Ic:\users\jraad\appdata\local\programs\python\python37\include -Ic:\users\jraad\appdata\local\programs\python\python37\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /Tcc/robustats.c /Fobuild\temp.win-amd64-3.7\Release\c/robustats.obj -std=c99
    cl : Command line warning D9002 : ignoring unknown option '-std=c99'
    robustats.c
    C:\Users\jraad\AppData\Local\Temp\pip-req-build-3zgly3fq\c\base.h(3): error C2059: syntax error: '<parameter-list>'
    c/robustats.c(101): warning C4244: 'function': conversion from 'int64_t' to 'double', possible loss of data
    c/robustats.c(261): warning C4244: '=': conversion from 'int64_t' to 'double', possible loss of data
    error: Command "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\jraad\appdata\local\programs\python\python37\lib\site-packages\numpy\core\include -Ic:\users\jraad\appdata\local\programs\python\python37\include -Ic:\users\jraad\appdata\local\programs\python\python37\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /Tcc/robustats.c /Fobuild\temp.win-amd64-3.7\Release\c/robustats.obj -std=c99" failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\jraad\appdata\local\programs\python\python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\jraad\\AppData\\Local\\Temp\\pip-req-build-3zgly3fq\\setup.py'"'"'; __file__='"'"'C:\\Users\\jraad\\AppData\\Local\\Temp\\pip-req-build-3zgly3fq\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\jraad\AppData\Local\Temp\pip-record-uvx51511\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\jraad\appdata\local\programs\python\python37\Include\robustats' Check the logs for full command output.`

**Comment by FilippoBovo** [comment]
@jraad, maybe it is the ternary operator `x ? y : z` that is not supported by your compiler.

You can try to replace the max function with the following:

```
double max(double a, double b)
{
   if (a >= b)
      return a;
   else
      return b;
}
```

Then, try to reinstall the package. Please, let me know if this solve the problem.

**Comment by jraad** [comment]
Is there any reason you're defining that function instead of using fmax?

**Comment by FilippoBovo** [comment]
Yes, because there is no need to import a library just for a simple function.

**Pull request closed without merging**
